Document: vma
Title: Debian vma Manual
Author: <insert document author here>
Abstract: This manual describes what vma is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vma/vma.sgml.gz

Format: postscript
Files: /usr/share/doc/vma/vma.ps.gz

Format: text
Files: /usr/share/doc/vma/vma.text.gz

Format: HTML
Index: /usr/share/doc/vma/html/index.html
Files: /usr/share/doc/vma/html/*.html
